// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package subgraph

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

type BlockFilter struct {
	Min int `json:"min"`
	Max int `json:"max"`
}

// GetMin returns BlockFilter.Min, and is useful for accessing the field via an interface.
func (v *BlockFilter) GetMin() int { return v.Min }

// GetMax returns BlockFilter.Max, and is useful for accessing the field via an interface.
func (v *BlockFilter) GetMax() int { return v.Max }

// GetMeterDataPointsMeterDataPointsMeterDataPointEdge includes the requested fields of the GraphQL type MeterDataPointEdge.
type GetMeterDataPointsMeterDataPointsMeterDataPointEdge struct {
	Node   GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint `json:"node"`
	Cursor string                                                                `json:"cursor"`
}

// GetNode returns GetMeterDataPointsMeterDataPointsMeterDataPointEdge.Node, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdge) GetNode() GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint {
	return v.Node
}

// GetCursor returns GetMeterDataPointsMeterDataPointsMeterDataPointEdge.Cursor, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdge) GetCursor() string { return v.Cursor }

// GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint includes the requested fields of the GraphQL type MeterDataPoint.
type GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint struct {
	TransactionId string                                                                       `json:"transactionId"`
	MeterNumber   int                                                                          `json:"meterNumber"`
	Timestamp     float64                                                                      `json:"timestamp"`
	Payload       GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload `json:"payload"`
}

// GetTransactionId returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint.TransactionId, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint) GetTransactionId() string {
	return v.TransactionId
}

// GetMeterNumber returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint.MeterNumber, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint) GetMeterNumber() int {
	return v.MeterNumber
}

// GetTimestamp returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint.Timestamp, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint) GetTimestamp() float64 {
	return v.Timestamp
}

// GetPayload returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint.Payload, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPoint) GetPayload() GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload {
	return v.Payload
}

// GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload includes the requested fields of the GraphQL type MeterDataPointPayload.
type GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload struct {
	Energy    float64 `json:"energy"`
	Nonce     int     `json:"nonce"`
	Voltage   float64 `json:"voltage"`
	Longitude float64 `json:"longitude"`
	Latitude  float64 `json:"latitude"`
	Signature string  `json:"signature"`
	PublicKey string  `json:"publicKey"`
}

// GetEnergy returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.Energy, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetEnergy() float64 {
	return v.Energy
}

// GetNonce returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.Nonce, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetNonce() int {
	return v.Nonce
}

// GetVoltage returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.Voltage, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetVoltage() float64 {
	return v.Voltage
}

// GetLongitude returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.Longitude, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetLongitude() float64 {
	return v.Longitude
}

// GetLatitude returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.Latitude, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetLatitude() float64 {
	return v.Latitude
}

// GetSignature returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.Signature, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetSignature() string {
	return v.Signature
}

// GetPublicKey returns GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload.PublicKey, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsMeterDataPointsMeterDataPointEdgeNodeMeterDataPointPayload) GetPublicKey() string {
	return v.PublicKey
}

// GetMeterDataPointsResponse is returned by GetMeterDataPoints on success.
type GetMeterDataPointsResponse struct {
	MeterDataPoints []GetMeterDataPointsMeterDataPointsMeterDataPointEdge `json:"meterDataPoints"`
}

// GetMeterDataPoints returns GetMeterDataPointsResponse.MeterDataPoints, and is useful for accessing the field via an interface.
func (v *GetMeterDataPointsResponse) GetMeterDataPoints() []GetMeterDataPointsMeterDataPointsMeterDataPointEdge {
	return v.MeterDataPoints
}

type MeterDataPointOrderBy string

const (
	MeterDataPointOrderByHeightAsc  MeterDataPointOrderBy = "HEIGHT_ASC"
	MeterDataPointOrderByHeightDesc MeterDataPointOrderBy = "HEIGHT_DESC"
)

var AllMeterDataPointOrderBy = []MeterDataPointOrderBy{
	MeterDataPointOrderByHeightAsc,
	MeterDataPointOrderByHeightDesc,
}

// __GetMeterDataPointsInput is used internally by genqlient
type __GetMeterDataPointsInput struct {
	MeterNumber int                   `json:"meterNumber"`
	Block       BlockFilter           `json:"block"`
	First       int                   `json:"first"`
	SortBy      MeterDataPointOrderBy `json:"sortBy"`
	After       string                `json:"after"`
}

// GetMeterNumber returns __GetMeterDataPointsInput.MeterNumber, and is useful for accessing the field via an interface.
func (v *__GetMeterDataPointsInput) GetMeterNumber() int { return v.MeterNumber }

// GetBlock returns __GetMeterDataPointsInput.Block, and is useful for accessing the field via an interface.
func (v *__GetMeterDataPointsInput) GetBlock() BlockFilter { return v.Block }

// GetFirst returns __GetMeterDataPointsInput.First, and is useful for accessing the field via an interface.
func (v *__GetMeterDataPointsInput) GetFirst() int { return v.First }

// GetSortBy returns __GetMeterDataPointsInput.SortBy, and is useful for accessing the field via an interface.
func (v *__GetMeterDataPointsInput) GetSortBy() MeterDataPointOrderBy { return v.SortBy }

// GetAfter returns __GetMeterDataPointsInput.After, and is useful for accessing the field via an interface.
func (v *__GetMeterDataPointsInput) GetAfter() string { return v.After }

// The query executed by GetMeterDataPoints.
const GetMeterDataPoints_Operation = `
query GetMeterDataPoints ($meterNumber: Int!, $block: BlockFilter, $first: Int!, $sortBy: MeterDataPointOrderBy, $after: String) {
	meterDataPoints(meterNumber: $meterNumber, block: $block, first: $first, sortBy: $sortBy, after: $after) {
		node {
			transactionId
			meterNumber
			timestamp
			payload {
				energy
				nonce
				voltage
				energy
				longitude
				latitude
				signature
				publicKey
			}
		}
		cursor
	}
}
`

func GetMeterDataPoints(
	ctx_ context.Context,
	client_ graphql.Client,
	meterNumber int,
	block BlockFilter,
	first int,
	sortBy MeterDataPointOrderBy,
	after string,
) (data_ *GetMeterDataPointsResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "GetMeterDataPoints",
		Query:  GetMeterDataPoints_Operation,
		Variables: &__GetMeterDataPointsInput{
			MeterNumber: meterNumber,
			Block:       block,
			First:       first,
			SortBy:      sortBy,
			After:       after,
		},
	}

	data_ = &GetMeterDataPointsResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
