ALTER TABLE users
DROP COLUMN name;

ALTER TABLE users
ADD COLUMN password_hash TEXT NOT NULL DEFAULT '';

ALTER TABLE users
ADD COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE TABLE sessions (
    id TEXT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    expires_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);